Find the ten best-selling games. The output should contain all the columns in the game_sales table and be sorted by the games_sold column in descending order. Save the output as best_selling_games.

Find the ten years with the highest average critic score, where at least four games were released (to ensure a good sample size). Return an output with the columns year, num_games released, and avg_critic_score. The avg_critic_score should be rounded to 2 decimal places. The table should be ordered by avg_critic_score in descending order. Save the output as critics_top_ten_years. Do not use the critics_avg_year_rating table provided; this has been provided for your third query.

Find the years where critics and users broadly agreed that the games released were highly rated. Specifically, return the years where the average critic score was over 9 OR the average user score was over 9. The pre-computed average critic and user scores per year are stored in users_avg_year_rating and critics_avg_year_rating tables respectively. The query should return the following columns: year, num_games, avg_critic_score, avg_user_score, and diff. The diff column should be the difference between the avg_critic_score and avg_user_score. The table should be ordered by the year in ascending order, save this as a DataFrame named golden_years.

In [31]:
-- best_selling_games
SELECT *
FROM game_sales
ORDER BY games_sold DESC
LIMIT 10;

                                        name platform  ... games_sold  year
0                         Wii Sports for Wii      Wii  ...      82.90  2006
1                  Super Mario Bros. for NES      NES  ...      40.24  1985
2    Counter-Strike: Global Offensive for PC       PC  ...      40.00  2012
3                     Mario Kart Wii for Wii      Wii  ...      37.32  2008
4       PLAYERUNKNOWN'S BATTLEGROUNDS for PC       PC  ...      36.60  2017
5                           Minecraft for PC       PC  ...      33.15  2010
6                  Wii Sports Resort for Wii      Wii  ...      33.13  2009
7  Pokemon Red / Green / Blue Version for GB       GB  ...      31.38  1998
8               New Super Mario Bros. for DS       DS  ...      30.80  2006
9          New Super Mario Bros. Wii for Wii      Wii  ...      30.30  2009

[10 rows x 6 columns]

In [32]:
-- critics_top_ten_years
SELECT g.year, COUNT(g.name) AS num_games, ROUND(AVG(r.critic_score),2) AS avg_critic_score
FROM game_sales g
JOIN reviews r ON g.name = r.name
GROUP BY g.year
HAVING COUNT(g.name) >= 4
ORDER BY avg_critic_score DESC
LIMIT 10;

   year  num_games  avg_critic_score
0  1998         10              9.32
1  2004         11              9.03
2  2002          9              8.99
3  1999         11              8.93
4  2001         13              8.82
5  2011         26              8.76
6  2016         13              8.67
7  2013         18              8.66
8  2008         20              8.63
9  2017         13              8.62

In [33]:
-- golden_years
SELECT u.year, u.avg_user_score, u.num_games, c.avg_critic_score, c.avg_critic_score - u.avg_user_score AS diff
FROM critics_avg_year_rating c
JOIN users_avg_year_rating u ON u.year = c.year
WHERE u.avg_user_score > 9 OR c.avg_critic_score > 9
ORDER BY year ASC;

   year  avg_user_score  num_games  avg_critic_score  diff
0  1997            9.50          8              7.93 -1.57
1  1998            9.40         10              9.32 -0.08
2  2004            8.55         11              9.03  0.48
3  2008            9.03         20              8.63 -0.40
4  2009            9.18         20              8.55 -0.63
5  2010            9.24         23              8.41 -0.83